[package]
name = "onthehour"
version = "3.0.0"
authors = ["Richard Dallaway <richard@dallaway.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
chrono-tz = "0.5.1"
tweetust = "0.10.0"
envy = "0.4.0"
serde = "1.0"
serde_derive = "1.0"
openssl-probe = "0.1.2"
